In [91]:
import pandas as pd
from tqdm import tqdm
import math
import numpy as np
import itertools as it

# tensor ranks

In [2]:
pd.read_csv('data/ranks_8x4x3.tsv', sep='\t')

                                                        T  rank
0       0000000000000000000000000000000000000000000000...     0
1       0000000000000000000000000000000000000000000000...     1
2       0000000000000000000000000000000000000000000000...     2
3       0000000000000000000000000000000000000000000000...     3
4       0000000000000000000000000000000000000000000000...     2
...                                                   ...   ...
158066  0000000010100000000100110000010001000000101000...    10
158067  0000000010100000000100110000010001000000101000...    10
158068  0000000010100000000100110000010001000000101000...    10
158069  0000000010100000000100110000010001000000101000...    10
158070  0000000010100000000101000000010001000000101000...    10

[158071 rows x 2 columns]

In [27]:
def collect_ranks(shape,path):
    df=pd.read_csv(path, sep='\t')
    size=math.prod(shape)
    out=[]
    for T_str,r in tqdm(zip(df['T'],df['rank'])):
        assert len(T_str)==size
        assert all(ch in '01' for ch in T_str)
        T=np.array([int(ch) for ch in T_str]).reshape(shape)
        out.append((T,r))
    return out

In [34]:
def print_report(shape,canonicals_path):
    pairs=collect_ranks(shape,canonicals_path)
    assert all(T.shape==shape for T,_ in pairs)
    for n0 in range(shape[0]+1):
        filtered_pairs=[(T,r) for T,r in pairs if (T!=0).any(axis=(1,2)).sum()<=n0]
        if len(filtered_pairs)==0:
            continue
        T,r=max(filtered_pairs,key=lambda p:p[1])
        print('='*64)
        print(f'shape={(n0,*shape[1:])}')
        display(T)
        print(f'\tn_canonicals={len(filtered_pairs)} max_rank={r}')

In [35]:
print_report((8,4,3),'data/ranks_8x4x3.tsv')

158071it [00:03, 44626.85it/s]

================================================================
shape=(0, 4, 3)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

	n_canonicals=1 max_rank=0
================================================================
shape=(1, 4, 3)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 1],
        [0, 1, 0],
        [1, 0, 0]]])

	n_canonicals=4 max_rank=3
================================================================
shape=(2, 4, 3)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 1],
        [0, 1, 0]],

       [[0, 0, 1],
        [0, 1, 0],
        [0, 0, 0],
        [1, 0, 0]]])

	n_canonicals=28 max_rank=5
================================================================
shape=(3, 4, 3)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 1]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 1],
        [0, 1, 0]],

       [[0, 0, 1],
        [0, 1, 0],
        [0, 0, 0],
        [1, 0, 0]]])

	n_canonicals=355 max_rank=6
================================================================
shape=(4, 4, 3)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 1],
        [0, 1, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 1, 0],
        [0, 1, 1]],

       [[0, 0, 1],
        [0, 1, 0],
        [0, 0, 0],
        [1, 0, 0]],

       [[0, 1, 0],
        [0, 1, 1],
        [1, 0, 0],
        [1, 0, 0]]])

	n_canonicals=5626 max_rank=8
================================================================
shape=(5, 4, 3)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 1],
        [0, 1, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 1, 0],
        [0, 1, 1]],

       [[0, 0, 1],
        [0, 1, 0],
        [0, 0, 0],
        [1, 0, 0]],

       [[0, 1, 0],
        [0, 1, 1],
        [1, 0, 0],
        [1, 0, 0]]])

	n_canonicals=42691 max_rank=8
================================================================
shape=(6, 4, 3)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 1]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 1, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [1, 0, 0]],

       [[0, 0, 0],
        [0, 0, 1],
        [0, 1, 0],
        [0, 0, 0]],

       [[0, 0, 1],
        [0, 0, 0],
        [1, 0, 0],
        [0, 0, 0]],

       [[0, 1, 0],
        [1, 0, 0],
        [0, 0, 1],
        [0, 0, 0]]])

	n_canonicals=115735 max_rank=9
================================================================
shape=(7, 4, 3)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 1]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 1, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [1, 0, 0]],

       [[0, 0, 0],
        [0, 0, 1],
        [0, 1, 0],
        [0, 0, 0]],

       [[0, 0, 1],
        [0, 0, 0],
        [1, 0, 0],
        [0, 0, 0]],

       [[0, 1, 0],
        [1, 0, 0],
        [0, 0, 1],
        [0, 0, 0]]])

	n_canonicals=152800 max_rank=9
================================================================
shape=(8, 4, 3)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 1]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 1, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [1, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 1],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 1, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 1],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 1],
        [0, 1, 0],
        [1, 0, 0],
        [0, 0, 0]],

       [[0, 1, 0],
        [1, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

	n_canonicals=158071 max_rank=10

In [36]:
print_report((4,4,4),'data/ranks_concise_4x4x4.tsv')

2279851it [00:36, 63244.85it/s]

================================================================
shape=(4, 4, 4)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 1],
        [0, 0, 1, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 1, 1]],

       [[0, 0, 0, 1],
        [0, 0, 1, 0],
        [0, 1, 0, 0],
        [1, 0, 0, 0]],

       [[0, 0, 1, 0],
        [0, 0, 1, 1],
        [1, 0, 0, 0],
        [1, 1, 0, 0]]])

	n_canonicals=2279851 max_rank=9

In [37]:
print_report((4,4,4),'data/ranks_non_concise_4x4x4.tsv')

15929it [00:00, 65139.46it/s]

================================================================
shape=(0, 4, 4)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

	n_canonicals=1 max_rank=0
================================================================
shape=(1, 4, 4)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 1],
        [0, 0, 1, 0],
        [0, 1, 0, 0],
        [1, 0, 0, 0]]])

	n_canonicals=5 max_rank=4
================================================================
shape=(2, 4, 4)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 1],
        [0, 0, 1, 0]],

       [[0, 0, 0, 1],
        [0, 0, 1, 0],
        [0, 1, 0, 0],
        [1, 0, 0, 0]]])

	n_canonicals=58 max_rank=6
================================================================
shape=(3, 4, 4)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 1],
        [0, 0, 1, 0]],

       [[0, 0, 0, 1],
        [0, 0, 1, 0],
        [0, 1, 0, 0],
        [1, 0, 0, 0]],

       [[0, 0, 1, 0],
        [0, 0, 1, 1],
        [1, 0, 0, 0],
        [1, 1, 0, 0]]])

	n_canonicals=5626 max_rank=8
================================================================
shape=(4, 4, 4)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 1],
        [0, 0, 1, 0]],

       [[0, 0, 0, 1],
        [0, 0, 1, 0],
        [0, 1, 0, 0],
        [1, 0, 0, 0]],

       [[0, 0, 1, 0],
        [0, 0, 1, 1],
        [1, 0, 0, 0],
        [1, 1, 0, 0]]])

	n_canonicals=15929 max_rank=8

# analyzing search costs

In [2]:
def parse_list(s):
    assert s[0]=='[' and s[-1]==']'
    out=[]
    for tok in s.removeprefix('[').removesuffix(']').split(','):
        tok=tok.strip()
        if len(tok)==0:
            continue
        out.append(int(tok))
    return out

In [3]:
parse_list('[1, 1, 16, 3258, 78695, 8902]')

[1, 1, 16, 3258, 78695, 8902]

In [5]:
parse_list('[ ]')

[]

In [18]:
df=pd.concat(
    [
        pd.read_csv('data/cpd_search_stats_concise_4x4x4.tsv', sep='\t'),
        pd.read_csv('data/cpd_search_stats_non_concise_4x4x4.tsv', sep='\t'),
    ],
    axis=0,
)

In [19]:
df

,T,R,nvisited,npruned
0,0000000000000001000000000000001000000000000001...,4,[1],[0]
1,0000000000000001000000000000001000000000000001...,5,"[1, 0]","[1, 0]"
2,0000000000000001000000000000001000000000000001...,6,"[1, 0, 0]","[1, 0, 0]"
3,0000000000000001000000000000001000000000000001...,7,"[1, 8, 11, 28]","[0, 7, 10, 0]"
4,0000000000000001000000000000001000000000000001...,4,[1],[0]
...,...,...,...,...
53275,0000000100100100000100100100000000100100001100...,4,[1],[0]
53276,0000000100100100000100100100000000100100001100...,5,"[1, 0]","[1, 0]"
53277,0000000100100100000100100100000000100100001100...,6,"[1, 0, 0]","[1, 0, 0]"
53278,0000000100100100000100100100000000100100001100...,7,"[1, 105, 5460, 5248]","[0, 0, 5306, 0]"
53279,0000000100100100000100100100000000100100001100...,8,"[1, 1, 1, 6, 31]","[0, 0, 0, 5, 0]"

In [7]:
def search_costs(df):
    costs={}
    for T,R,s in tqdm(zip(df['T'],df['R'],df['nvisited'],strict=True)):
        costs[T]=costs.get(T,0)+sum(parse_list(s))
    return costs

In [20]:
costs=search_costs(df)

10652821it [00:20, 530605.33it/s]

In [21]:
dict(sorted(costs.items(),key=(lambda p:p[1]),reverse=True)[:5])

{'0000000100100100000000100011100000010000010001100010000010001011': 3025933,
 '0000000100100100000100100000100000100100111010010100111000110101': 2019006,
 '0000000100100100000000100100100000010100110001000010110001011010': 1923039,
 '0000000100100100000000100100100000100100100001010100100000111010': 1839764,
 '0000000100100100000000100100100000100100100000010100100000111010': 1827721}

In [22]:
vals=np.array(list(costs.values()))
display(vals)

vals.mean(),np.exp(np.log(vals).mean())

array([   51,    50,    51, ...,    38, 10872, 10857])

/var/folders/8c/clq2thnn1jdcdvbmmvhlvb8m0000gn/T/ipykernel_29889/508985524.py:4: RuntimeWarning: divide by zero encountered in log
  vals.mean(),np.exp(np.log(vals).mean())

(11961.79638075077, 0.0)

In [10]:
for name in [
    '5x4x3',
    '6x4x3',
    '7x4x3',
    '8x4x3',
]:
    df=pd.read_csv(f'data/cpd_search_stats_{name}.tsv', sep='\t')
    costs=search_costs(df)

    print('highest costs')
    display(dict(sorted(costs.items(),key=(lambda p:p[1]),reverse=True)[:5]))

    vals=np.array(list(costs.values()))
    display(vals)

    print(name,vals.mean(),np.exp(np.log(vals).mean()))

137916it [00:00, 566818.61it/s]

highest costs

{'000000000000000000001010000000010100001010100000010100000101': 80242,
 '000000000000000000001010000000010100001010100000010100000011': 78205,
 '000000000000000000001010000000010011001010000100010011100100': 73435,
 '000000000000000000001010000100010011001010000100010011110010': 36670,
 '000000000001000001010100001100000010010100111000100110100100': 26933}

array([  0,   1,   3, ..., 813, 523, 325])

/var/folders/8c/clq2thnn1jdcdvbmmvhlvb8m0000gn/T/ipykernel_27942/3847984599.py:16: RuntimeWarning: divide by zero encountered in log
  print(name,vals.mean(),np.exp(np.log(vals).mean()))

5x4x3 644.6359420018271 0.0

350748it [00:00, 588538.95it/s]

highest costs

{'000000000000000000000000000000001010000000010100001010100000010100000101': 80242,
 '000000000000000000000000000000001010000000010100001010100000010100000011': 78205,
 '000000000000000000000000000000001010000000010011001010000100010011100100': 73435,
 '000000000000000000000000000000001010000100010011001010000100010011110010': 36670,
 '000000000001000000000010000000000100000001010000001000100000010100001000': 34959}

array([   0,    1,    3, ..., 5683,  261, 5708])

/var/folders/8c/clq2thnn1jdcdvbmmvhlvb8m0000gn/T/ipykernel_27942/3847984599.py:16: RuntimeWarning: divide by zero encountered in log
  print(name,vals.mean(),np.exp(np.log(vals).mean()))

6x4x3 611.1480796647513 0.0

446281it [00:00, 617590.03it/s]

highest costs

{'000000000000000000000000000000000000000000001010000000010100001010100000010100000101': 80242,
 '000000000000000000000000000000000000000000001010000000010100001010100000010100000011': 78205,
 '000000000000000000000000000000000000000000001010000000010011001010000100010011100100': 73435,
 '000000000000000000000000000000000000000000001010000100010011001010000100010011110010': 36670,
 '000000000000000000000000000000000000000001010100001000100110010100010101100110111010': 16357}

array([  0,   1,   3, ..., 223, 223, 112])

/var/folders/8c/clq2thnn1jdcdvbmmvhlvb8m0000gn/T/ipykernel_27942/3847984599.py:16: RuntimeWarning: divide by zero encountered in log
  print(name,vals.mean(),np.exp(np.log(vals).mean()))

7x4x3 384.0437565445026 0.0

456730it [00:00, 592740.89it/s]

highest costs

{'000000000000000000000000000000000000000000000000000000001010000000010100001010100000010100000101': 80242,
 '000000000000000000000000000000000000000000000000000000001010000000010100001010100000010100000011': 78205,
 '000000000000000000000000000000000000000000000000000000001010000000010011001010000100010011100100': 73435,
 '000000000000000000000000000000000000000000000000000000001010000100010011001010000100010011110010': 36670,
 '000000000000000000000000000000000000000000000000000001010100001000100110010100010101100110111010': 16357}

array([  0,   1,   3, ..., 110, 110, 110])

8x4x3 352.3834542705493 0.0

/var/folders/8c/clq2thnn1jdcdvbmmvhlvb8m0000gn/T/ipykernel_27942/3847984599.py:16: RuntimeWarning: divide by zero encountered in log
  print(name,vals.mean(),np.exp(np.log(vals).mean()))

# LaTeX

In [48]:
from ast import literal_eval

In [ ]:
[[Tensor([3], [1, 1, 1]), Tensor([4], [1, 0, 0, 1]), Tensor([4], [1, 0, 1, 0])], [Tensor([3], [1, 0, 0]), Tensor([4], [1, 0, 1, 1]), Tensor([4], [1, 0, 0, 1])], [Tensor([3], [1, 0, 1]), Tensor([4], [1, 0, 1, 0]), Tensor([4], [1, 0, 0, 0])], [Tensor([3], [1, 0, 0]), Tensor([4], [0, 0, 0, 1]), Tensor([4], [0, 0, 0, 1])], [Tensor([3], [0, 0, 1]), Tensor([4], [0, 1, 0, 0]), Tensor([4], [0, 1, 0, 1])], [Tensor([3], [0, 1, 1]), Tensor([4], [0, 1, 0, 1]), Tensor([4], [0, 1, 1, 0])], [Tensor([3], [0, 1, 0]), Tensor([4], [0, 1, 1, 1]), Tensor([4], [0, 1, 0, 0])], [Tensor([3], [1, 1, 0]), Tensor([4], [1, 0, 0, 0]), Tensor([4], [1, 0, 1, 1])]]

In [65]:
def get_fac_mats(s):
    trimmed=''.join(c for c in s if c not in 'Tensor')
    trimmed=''.join(trimmed.split())  # remove whitespace
    cpd_vecs=literal_eval(trimmed)
    fac_mats=[]
    for vecs in zip(*cpd_vecs):
        vec0=vecs[0]
        assert all(vec0[0]==v[0] for v in vecs)
        M=np.stack([v for _,v in vecs],axis=-1)
        fac_mats.append(M)
    return fac_mats

In [67]:
get_fac_mats('[[Tensor([6], [1, 0, 0, 0, 0, 0]), Tensor([4], [0, 0, 0, 1]), Tensor([3], [0, 0, 1])], [Tensor([6], [0, 1, 0, 0, 0, 0]), Tensor([4], [0, 0, 0, 1]), Tensor([3], [0, 1, 0])], [Tensor([6], [0, 0, 1, 0, 0, 0]), Tensor([4], [0, 0, 0, 1]), Tensor([3], [1, 0, 0])], [Tensor([6], [0, 0, 0, 1, 0, 0]), Tensor([4], [0, 1, 0, 0]), Tensor([3], [0, 0, 1])], [Tensor([6], [0, 0, 0, 0, 1, 0]), Tensor([4], [1, 0, 1, 0]), Tensor([3], [1, 1, 1])], [Tensor([6], [0, 0, 0, 0, 0, 1]), Tensor([4], [1, 1, 0, 0]), Tensor([3], [1, 0, 0])], [Tensor([6], [0, 0, 0, 0, 1, 1]), Tensor([4], [0, 0, 1, 0]), Tensor([3], [0, 0, 1])], [Tensor([6], [0, 0, 0, 1, 1, 0]), Tensor([4], [0, 0, 1, 0]), Tensor([3], [0, 1, 0])], [Tensor([6], [0, 0, 0, 0, 1, 1]), Tensor([4], [1, 0, 0, 0]), Tensor([3], [1, 1, 0])]]')

[array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1, 0, 1, 1, 1],
        [0, 0, 0, 0, 0, 1, 1, 0, 1]]),
 array([[0, 0, 0, 0, 1, 1, 0, 0, 1],
        [0, 0, 0, 1, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 1, 1, 0],
        [1, 1, 1, 0, 0, 0, 0, 0, 0]]),
 array([[0, 0, 1, 0, 1, 1, 0, 0, 1],
        [0, 1, 0, 0, 1, 0, 0, 1, 1],
        [1, 0, 0, 1, 1, 0, 1, 0, 0]])]

In [66]:
get_fac_mats('[[Tensor([3], [1, 1, 1]), Tensor([4], [1, 0, 0, 1]), Tensor([4], [1, 0, 1, 0])], [Tensor([3], [1, 0, 0]), Tensor([4], [1, 0, 1, 1]), Tensor([4], [1, 0, 0, 1])], [Tensor([3], [1, 0, 1]), Tensor([4], [1, 0, 1, 0]), Tensor([4], [1, 0, 0, 0])], [Tensor([3], [1, 0, 0]), Tensor([4], [0, 0, 0, 1]), Tensor([4], [0, 0, 0, 1])], [Tensor([3], [0, 0, 1]), Tensor([4], [0, 1, 0, 0]), Tensor([4], [0, 1, 0, 1])], [Tensor([3], [0, 1, 1]), Tensor([4], [0, 1, 0, 1]), Tensor([4], [0, 1, 1, 0])], [Tensor([3], [0, 1, 0]), Tensor([4], [0, 1, 1, 1]), Tensor([4], [0, 1, 0, 0])], [Tensor([3], [1, 1, 0]), Tensor([4], [1, 0, 0, 0]), Tensor([4], [1, 0, 1, 1])]]')

[array([[1, 1, 1, 1, 0, 0, 0, 1],
        [1, 0, 0, 0, 0, 1, 1, 1],
        [1, 0, 1, 0, 1, 1, 0, 0]]),
 array([[1, 1, 1, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1, 1, 1, 0],
        [0, 1, 1, 0, 0, 0, 1, 0],
        [1, 1, 0, 1, 0, 1, 1, 0]]),
 array([[1, 1, 1, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1, 1, 1, 0],
        [1, 0, 0, 0, 0, 1, 0, 1],
        [0, 1, 0, 1, 1, 0, 0, 1]])]

# lower bounds on R(5,4,4)

In [101]:
from collections.abc import Sequence

import numpy as np
import numpy.typing as npt
from numba import njit

from functools import partial

tqdm = partial(tqdm, position=0)

Tensor = npt.NDArray[np.int64]


@njit
def mexp(n: int, k: int, MOD: int):
    """
    return n^k modulo MOD
    """
    assert k >= 0
    if k == 0:
        return 1
    h = mexp(n, k // 2, MOD)
    h = (h * h) % MOD
    return h if k % 2 == 0 else (n * h) % MOD


@njit
def minv(n: int, MOD: int):
    """
    return the multiplicative inverse of n modulo MOD
    assume MOD is prime
    """
    assert n != 0
    return mexp(n, MOD - 2, MOD)


@njit
def is_prime(n: int):
    assert n > 0
    if n == 1:
        return False
    i = 2
    while i * i <= n:
        if n % i == 0:
            return False
        i += 1
    return True


@njit
def mat_row_reduce(
    M: Tensor,
    MOD: int,
):
    """
    return (Q,rM,r) s.t.
    * r = rank(M)
    * Q invertible
    * rM = rref(M)
    * Q@M = rM
    assume MOD is prime
    """
    # NOTE no bounds checking in numba
    assert is_prime(MOD)
    assert M.ndim == 2, "not matrix"
    assert ((M >= 0) & (M < MOD)).all(), (M, MOD)
    M = np.copy(M)
    m, n = M.shape
    Q = np.eye(m, dtype=np.int64)
    r = 0
    for j in range(n):
        i0 = -1
        for i in range(r, m):
            if M[i, j] != 0:
                i0 = i
                break
        if i0 == -1:
            continue

        for k in range(n):
            M[r, k], M[i0, k] = M[i0, k], M[r, k]
        for k in range(m):
            Q[r, k], Q[i0, k] = Q[i0, k], Q[r, k]

        s = minv(M[r, j], MOD)
        for k in range(n):
            M[r, k] = (M[r, k] * s) % MOD
        for k in range(m):
            Q[r, k] = (Q[r, k] * s) % MOD

        for i in range(m):
            if i != r:
                s = -M[i, j]
                for k in range(n):
                    M[i, k] = (M[i, k] + s * M[r, k]) % MOD
                for k in range(m):
                    Q[i, k] = (Q[i, k] + s * Q[r, k]) % MOD
        r += 1

    return Q, M, r


@njit
def mat_rank(M: Tensor, MOD: int):
    assert is_prime(MOD)
    assert M.ndim == 2, "not matrix"
    assert ((M >= 0) & (M < MOD)).all(), (M, MOD)
    M = np.copy(M)
    m, n = M.shape
    r = 0
    for j in range(n):
        i0 = -1
        for i in range(r, m):
            if M[i, j] != 0:
                i0 = i
                break
        if i0 == -1:
            continue

        for k in range(n):
            M[r, k], M[i0, k] = M[i0, k], M[r, k]

        s = minv(M[r, j], MOD)
        for k in range(n):
            M[r, k] = (M[r, k] * s) % MOD

        for i in range(r + 1, m):  # forward reduction only
            s = -M[i, j]
            for k in range(n):
                M[i, k] = (M[i, k] + s * M[r, k]) % MOD
        r += 1

    return r


def mat_is_inv(M: Tensor, MOD: int):
    assert M.ndim == 2
    n = M.shape[0]
    return n == M.shape[1] and mat_rank(M, MOD) == n


def mat_inv(M: Tensor, MOD: int):
    assert M.ndim == 2
    assert M.shape[0] == M.shape[1]
    n, _ = M.shape
    Q, _, r = mat_row_reduce(M, MOD)
    assert r == n
    return Q


def axis_op(M: Tensor, T: Tensor, ax: int, MOD: int) -> Tensor:
    """
    return tensor T' such that
    T'[i_0,...,i'_ax,...,i_{D-1}] = sum_{i_ax} M[i'_ax,i_ax]*T[i_0,...,i_{D-1}]
    """
    assert M.ndim == 2
    assert 0 <= ax < T.ndim
    # np.dot(A,B) contracts last axis of A with 2nd-last axis of B
    # (t0 ... ta ...) (m1 m0)  transpose M
    # (t0 ... t[a-1] t[D-1] t[a+1] ... t[D-2] ta) (m1 m0)  swap axes of T
    # t0 ... t[a-1] t[D-1] t[a+1] ... t[D-2] m0  np.dot
    # t0 ... t[a-1] m0 t[a+1] ... t[D-2] t[D-1] swap back
    return np.dot(T.swapaxes(ax, T.ndim - 1), M.T).swapaxes(ax, T.ndim - 1) % MOD


def axis_ops(Ms: Sequence[Tensor | None], T: Tensor, MOD: int):
    assert len(Ms) == T.ndim, f"{(T.ndim,Ms)=}"
    out = T
    for d, M in enumerate(Ms):
        if M is not None:
            out = axis_op(M, out, d, MOD)
    return out

def all_tensors(sh: tuple[int, ...], MOD: int):
    for v in it.product(range(MOD), repeat=math.prod(sh)):
        yield np.array(v, dtype=int).reshape(sh)

def all_augments(T: Tensor, MOD: int):
    assert T.ndim >= 1
    for M in all_tensors((1, *T.shape[1:]), MOD):
        yield np.concatenate([T, M], axis=0)

def lex_code(T: Tensor) -> tuple[int, ...]:
    return tuple(T.flatten().tolist())

def canonical0(T: Tensor, MOD: int):
    n0 = T.shape[0]
    if n0 == 0:
        return T
    sorted_vecs = sorted(
        all_tensors((n0,), MOD),
        key=lambda v: lex_code(axis_op(v[None, :], T, 0, MOD)),
    )
    good: list[Tensor] = []
    for v in sorted_vecs:
        if mat_rank(np.stack([*good, v]), MOD) > len(good):
            good.append(v)
    return axis_op(np.stack(good), T, 0, MOD)

In [104]:
T444=np.array([
    0,0,0,0,
    0,0,0,0,
    0,0,0,1,
    0,0,1,0,

    0,0,0,0,
    0,0,0,0,
    0,0,1,0,
    0,0,1,1,

    0,0,0,1,
    0,0,1,0,
    0,1,0,0,
    1,0,0,0,

    0,0,1,0,
    0,0,1,1,
    1,0,0,0,
    1,1,0,0,
]).reshape((4,4,4))
MOD=2

augs=[]
seen=set()
for T in tqdm(all_augments(T444,MOD)):
    T=canonical0(T,MOD)
    code=lex_code(T)
    if code not in seen:
        seen.add(code)
        augs.append(T)

65536it [00:31, 2103.66it/s]

In [105]:
with open('data/aug_444_544.txt','w') as f:
    lines=[]
    for T in tqdm(augs):
        lines.append(
            ''.join(str(v) for v in T.flatten())
        )
    f.write('\n'.join(lines))

100%|████████████████████████████████████| 4096/4096 [00:00<00:00, 39558.79it/s]

In [116]:
for shape in [
#     (k,4,4)
#     for k in range(5,7)
    (2,2,2)
]:
    n_tensors=1000

    np.random.seed(hash(shape)%(2**32))
    Ts=[
        np.random.randint(low=0,high=2,size=shape)
        for _ in range(n_tensors)
    ]

    shape_name='x'.join(str(v) for v in shape)
    with open(f'data/rand_{shape_name}.txt','w') as f:
        lines=[''.join(str(v) for v in T.flatten()) for T in Ts]
        f.write('\n'.join(lines))